### ISSUE TITLE
func: batch_anneal的作用是？

### ISSUE THREAD

**Issue by shihanmax** [chncyhn/simulated-annealing-tsp#2]
batch_anneal是为了多次从初始化状态运行模拟退火，相当于寻找time次中的最优解吗

**Comment by shihanmax** [comment]
这里执行time次，其实并不会对整体结果有影响吧，因为每次都从一个随机的初始状态开始？不知道我的理解是否正确

**Comment by chncyhn** [comment]
Hello @shihanmax , note that this is a heuristic-driven solution. So we do not _know_ if we have found the optimal solution after executing simulated annealing once. 
  
Depending on the random initialization, we can get to different solutions. By running the annealing multiple times with different random initializations, we gather a bunch of solutions, and choose the "most optimal" one among those as our final result.

**Comment by shihanmax** [comment]
Thank you for the detailed explanation, by the way, I have another question, which is not really on this topic, that is if I generate a high quality disturbance of random input on every sampling time, could I make the algorithm convergent more quickly?

**Comment by chncyhn** [comment]
Hey @shihanmax, sorry I now realize that I have misexplained the idea a bit. The input is the same in each run. The randomness comes from the algorithm itself.   
  
You can see in the code how candidate improvements are generated in the algorithm: It's by randomly reversing part of the current path.  
  
Each round we start with the same initial state (which is the result of the greedy closest-neighbor solution). Rounds diverge after this point as the following solutions depend on the random seed.

**Comment by shihanmax** [comment]
Hello @chncyhn, I got your meaning, what I wrote at the last message is about another question, If we can control the "randomness" of the algorithm (say to restrict the random procedure with some prior knowledge),could we make the SA algorithm convergent more quickly?

**Comment by chncyhn** [comment]
@shihanmax Yes that'd definitely be possible. The two most obvious ways to make the algorithm converge more quickly are:  
  
- Improve the random solution generation (as you suggested). Perhaps instead of purely random, it can be a bit smarter.  
- Improve the initial solution. Currently, the closest-neighbor heuristic is used, but perhaps different methods to gain an initial solution would help us converge faster, or converge to more optimal solutions.

**Comment by shihanmax** [comment]
It's helpful, thanks!

**Comment by shihanmax** [comment]
It's helpful, thanks!
