### ISSUE TITLE
Euclidean Distance function

### ISSUE THREAD

**Issue by kamleshsahoo** [chncyhn/simulated-annealing-tsp#4]
Thanks , for this informative repo. While using the coords.txt file for the node coordinates, I found the Euclidean distance function refers the x- coordinates of a node with indices 0 and the y-coordinates by indices 1. I think they should be respectively 1 and 2 because the 0 indices are the node numbers. I separately tested with the modified indices and got the distance equal to that calculated manually. Please correct me if my understanding is wrong? Below is the snippet of the dist function with modified indices:
```
 def dist(self, node_0, node_1):
        """
        Euclidean distance between two nodes.
        """
        coord_0, coord_1 = self.coords[node_0], self.coords[node_1]
        return math.sqrt((coord_0[1] - coord_1[1]) ** 2 + (coord_0[2] - coord_1[2]) ** 2)
```

**Comment by chncyhn** [comment]
Great catch! 

It's not that these should be indexed 1 and 2 -- it's that the data should not include node numbers (which is not used at all). So the graph topology in `data.txt` is not solved incorrectly, it's just that we read the node ids as the x coord, and the x coord as the y coord, so we solve for a different topology.

I've removed the node ids from `data.txt` now. Thanks for pointing out!
